apiVersion: kubecontrolplane.config.openshift.io/v1
kind: KubeAPIServerConfig
storageConfig:
  ca: /var/run/configmaps/etcd-serving-ca/ca-bundle.crt
  certFile: /var/run/secrets/etcd-client/tls.crt
  keyFile: /var/run/secrets/etcd-client/tls.key
  urls: {{range .EtcdServerURLs}}
  - {{.}}{{end}}
