apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-kube-apiserver
  name: apiserver
  labels:
    app: openshift-kube-apiserver
    apiserver: "true"
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: openshift-kube-apiserver
      apiserver: "true"
  template:
    metadata:
      name: openshift-kube-apiserver
      labels:
        app: openshift-kube-apiserver
        apiserver: "true"
    spec:
      serviceAccountName: openshift-kube-apiserver-sa
      containers:
      - name: apiserver
        image: ${IMAGE}
        imagePullPolicy: IfNotPresent
        command: ["hypershift", "openshift-kube-apiserver"]
        args:
        - "--config=/var/run/configmaps/config/config.yaml"
        ports:
        - containerPort: 8443
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        - mountPath: /var/run/secrets/serving-cert
          name: serving-cert
      volumes:
      - name: serving-cert
        secret:
          secretName: serving-cert
      - name: config
        configMap:
          name: deployment-apiserver-config



