apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-signed-by: service-serving
  labels:
    app: openshift-cluster-kube-apiserver-operator
  name: metrics
  namespace: openshift-cluster-kube-apiserver-operator
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: openshift-cluster-kube-apiserver-operator
  sessionAffinity: None
  type: ClusterIP
