apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubeapiservers.operator.openshift.io
spec:
  scope: Cluster
  group: operator.openshift.io
  version: v1
  names:
    kind: KubeAPIServer
    plural: kubeapiservers
    singular: kubeapiserver
  subresources:
    status: {}
