apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cluster-kube-apiserver-operator
  namespace: openshift-cluster-kube-apiserver-operator
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    metricRelabelings:
    - action: drop
      regex: etcd_(debugging|disk|request|server).*
      sourceLabels:
      - __name__
    port: https
    scheme: https
    tlsConfig:
      # TODO where do you mount the service-ca.crt?
      insecureSkipVerify: true
      serverName: metrics.openshift-cluster-kube-apiserver-operator.svc
  jobLabel: component
  namespaceSelector:
    matchNames:
    - openshift-cluster-kube-apiserver-operator
  selector:
    matchLabels:
      app: openshift-cluster-kube-apiserver-operator
