apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: apiserver
  name: kube-apiserver
  namespace: openshift-kube-apiserver
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    metricRelabelings:
    - action: drop
      regex: etcd_(debugging|disk|request|server).*
      sourceLabels:
      - __name__
    - action: drop
      regex: apiserver_admission_controller_admission_latencies_seconds_.*
      sourceLabels:
      - __name__
    - action: drop
      regex: apiserver_admission_step_admission_latencies_seconds_.*
      sourceLabels:
      - __name__
    port: https
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      serverName: kubernetes
  jobLabel: component
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      component: apiserver
      provider: kubernetes
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-apiserver
  namespace: openshift-kube-apiserver
spec:
  groups:
  - name: using-deprecated-apis
    rules:
    - alert: UsingDeprecatedAPIAppsV1Beta1
      annotations:
        message: A client in the cluster is using deprecated apps/v1beta1 API that will be removed soon.
      expr: |
        apiserver_request_count{group="apps",version="v1beta1"}
      labels:
        severity: warning
    - alert: UsingDeprecatedAPIAppsV1Beta2
      annotations:
        message: A client in the cluster is using deprecated apps/v1beta2 API that will be removed soon.
      expr: |
        apiserver_request_count{group="apps",version="v1beta2"}
      labels:
        severity: warning
    - alert: UsingDeprecatedAPIExtensionsV1Beta1
      annotations:
        message: A client in the cluster is using deprecated extensions/v1beta1 API that will be removed soon.
      expr: |
        apiserver_request_count{group="extensions",version="v1beta1",resource!~"ingresses|",client!~"hyperkube/.*|cluster-policy-controller/.*"}
      labels:
        severity: warning
