apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: kube-system
spec:
  selector:
    openshift.io/component: etcd
  ports:
  - name: etcd
    port: 2379
    protocol: TCP
  - name: legacy-etcd
    port: 4001
    targetPort: 2379
    protocol: TCP
