apiVersion: v1
kind: Secret
metadata:
  name: kubelet-client
  namespace: {{ .Namespace }}
type: SecretTypeTLS
data:
  tls.crt: {{ .KubeletClientCertCrt | base64 }}
  tls.key: {{ .KubeletClientCertKey | base64 }}
