apiVersion: v1
kind: Secret
metadata:
  name: etcd-client
  namespace: {{ .Namespace }}
type: SecretTypeTLS
data:
  tls.crt: {{ .EtcdClientCertCrt | base64 }}
  tls.key: {{ .EtcdClientCertKey | base64 }}
