apiVersion: v1
kind: Secret
metadata:
  name: aggregator-client
  namespace: {{ .Namespace }}
type: SecretTypeTLS
data:
  tls.crt: {{ .Assets | load "apiserver-proxy.crt" | base64 }}
  tls.key: {{ .Assets | load "apiserver-proxy.key" | base64 }}
