apiVersion: v1
kind: Secret
metadata:
  name: kubelet-client
  namespace: {{ .Namespace }}
type: SecretTypeTLS
data:
  tls.crt: {{ .Assets | load "master.kubelet-client.crt" | base64 }}
  tls.key: {{ .Assets | load "master.kubelet-client.key" | base64 }}
