apiVersion: v1
kind: Secret
metadata:
  name: etcd-client
  namespace: {{ .Namespace }}
type: SecretTypeTLS
data:
  tls.crt: {{ .Assets | load "etcd-client.crt" | base64 }}
  tls.key: {{ .Assets | load "etcd-client.key" | base64 }}
