apiVersion: v1
kind: Secret
metadata:
  name: aggregator-client
  namespace: {{ .Namespace }}
type: SecretTypeTLS
data:
  tls.crt: {{ .AggregatorClientCertCrt | base64 }}
  tls.key: {{ .AggregatorClientCertKey | base64 }}
