apiVersion: v1
kind: Secret
metadata:
  name: serving-cert
  namespace: {{ .Namespace }}
type: SecretTypeTLS
data:
  tls.crt: {{ .Assets | load "master.server.crt" | base64 }}
  tls.key: {{ .Assets | load "master.server.key" | base64 }}
