apiVersion: v1
kind: ConfigMap
metadata:
  name: sa-token-signing-certs
  namespace: openshift-config-managed
data:
  service-account-001.pub: |
    {{ .Assets | load "service-account.pub" | indent 4 }}
