apiVersion: v1
kind: Secret
metadata:
  name: etcd-client
  namespace: kube-system
  labels:
    tier: "control-plane"
    k8s-app: "kube-apiserver"
    openshift.io/control-plane: "true"
    openshift.io/component: "api"
type: SecretTypeTLS
data:
  tls.crt: {{ .Assets | load "etcd-client.crt" | base64 }}
  tls.key: {{ .Assets | load "etcd-client.key" | base64 }}
