apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator-client-ca
  namespace: kube-system
  labels:
    tier: "control-plane"
    k8s-app: "kube-apiserver"
    openshift.io/control-plane: "true"
    openshift.io/component: "api"
data:
  ca-bundle.crt: |
    {{ .Assets | load "aggregator-ca.crt" | indent 4 }}
