apiVersion: v1
kind: Secret
metadata:
  name: next-bound-service-account-signing-key
  namespace: openshift-kube-apiserver-operator
  annotations: {{- if .UserProvidedBoundSASigningKey}}
    "auth.openshift.io/user-supplied-bound-token-key": "true" {{end}}
data: 
{{- if .UserProvidedBoundSASigningKey}}
  service-account.key: {{ .Assets | load "bound-service-account-signing-key.key" | base64 }}
  service-account.pub: {{ .Assets | load "bound-service-account-signing-key.pub" | base64 }}
{{- end}}