apiVersion: v1
kind: Secret
metadata:
  name: initial-kubelet-client
  namespace: openshift-config
type: SecretTypeTLS
data:
  tls.crt: {{ .Assets | load "apiserver.crt" | base64 }}
  tls.key: {{ .Assets | load "apiserver.key" | base64 }}
